### ISSUE TITLE
Access to the camera for Chrome on iOS

### ISSUE THREAD

**Issue by brovikov** [cozmo/jsQR#127]
It works good for all browsers on Android. But for Chrome and FireFox on iPhone it not connecting to the camera. Even not asking permit. Any idea how to fix that?

**Comment by kimdah3** [comment]
It seems camera access only works in native Safari and not in other browsers on iOS-devices. 
[Chrome and Firefox are not able to access iPhone Camera](https://stackoverflow.com/questions/51501642/chrome-and-firefox-are-not-able-to-access-iphone-camera)

**Comment by cozmo** [comment]
From my understanding what @kimdah3 said is correct. That said jsQR is[designed to be completely independent from webcams](https://github.com/cozmo/jsqr#a-note-on-webcams), and as such I'm not going to be super helpful in debugging webcam issues. As such I'm closing this issue, but if you think this is in error or if you have additional questions please comment/re-open.
