### ISSUE TITLE
autofocus failes with realteak cam

### ISSUE THREAD

**Issue by thomastrinamix** [cozmo/jsQR#137]
autofocus on realteak 0bda:5876 webcam (Lenovo 330 ideapad) does not work.

Additional Focus Option missing

**Comment by cozmo** [comment]
I don't know anything about how to configure autofocus with javascript, sorry. 

As mentioned in the [README](https://github.com/cozmo/jsQR#a-note-on-webcams) jsQR is designed to have no webcam specific implementation details. Rather the API is designed to take in image data and output any QR codes found within. Handling reading image data from the webcam and passing it to jsQR is the responsibility of the consumer, and as such you'll know more than me
