### ISSUE TITLE
It isn't working on DataMatrix.

### ISSUE THREAD

**Issue by kivancbeser** [cozmo/jsQR#144]
I try to read DataMatrix but this component doesn't work. Do you have any ideas? Is this development planned?

**Comment by cozmo** [comment]
DataMatrixs are a completely different type of barcode than QR codes, and this library only supports QR codes. I imagine there is probably some code re-use that could happen, but not a ton. If you are interested in created DataMatrix.js let me know and I'd be happy to share some of the lessons learned from creating jsQR, but as the project currently stands it won't scan a DataMatrix and I don't currently have plans to add that in the future.
