### ISSUE TITLE
Only partial QR content string URL

### ISSUE THREAD

**Issue by Proberts** [cozmo/jsQR#15]
When I decode this QR code:

![qr](https://cloud.githubusercontent.com/assets/778115/20866171/c2200d34-b9da-11e6-8a1b-1c6fd0a03ea8.png)

With zxing.org I get:

HTTPS://API.NICETOMEET.ME/api/getmecard.php?nuid=9msSjd5YdOSOHxHbbTLlyesPC4V2&mid=9695d152212c894ee74bb07f0f551ea5

With jsQR I get:

api/getmecard.php?nuid=9msSjd5YdOSOHxHbbTLlyesPC4V2&mid=9695d152212c894ee74bb07f0f551ea5

I've verified it as far as: the input to byteArrayToString() does not contain the first part of the URL.

**Comment by cozmo** [comment]
Great report - I'll take a look soon - sorry about any trouble :(
