### ISSUE TITLE
Does not work on Samaung Note 10 plus?

### ISSUE THREAD

**Issue by ScofieldYeh** [cozmo/jsQR#158]
I try the code on my Samaung Note 10 plus. Chrome does not turn on the camera after I gave it the permission.  It works on Firefox on the same phone. Is there any way to make it work on Chrome?

**Comment by cozmo** [comment]
This library [is a QR code scanner, and has no logic for camera access](https://github.com/cozmo/jsQR#a-note-on-webcams). 

If you can confirm this is an issue with jsQR - aka not related to the webcam access, but rather to the call of this library, then feel free to clarify in the issue, however if you're just having trouble getting `getUserMedia` to work I'm unfortunately not going to be able to help much.

Perhaps get your webcam capturing to work and then add jsQR and see if you can isolate the issue from there?

Closing this issue until it's clear it's an issue with jsQR not the webcam capture. Please comment/re-open if you feel this is in error.
