### ISSUE TITLE
How can I use this in Typescript for generating QR Code using Ionic 4??

### ISSUE THREAD

**Issue by Ragul184** [cozmo/jsQR#161]
Im currently developing a ionic event manager app which requires qr generator... I dont know how to use this jsQR for generating QR in ionic 4... If anyone knows kindly please respond to this and clear my doubts...

**Comment by cozmo** [comment]
This library cannot create QR codes, only scan them. There are other libraries on NPM that can create them, but I do not know if they're written in typescript etc (I don't know very much about them in general).
