### ISSUE TITLE
Detach user camera

### ISSUE THREAD

**Issue by gkucmierz** [cozmo/jsQR#17]
I am trying detaching user camera when its not needed.

I was trying to call pause() on video
I was trying change video.src
Maybe something should be done on media stream?

I hope someone here know much more than me how is that working, and tell me how to detach attached camera from app.

**Comment by gkucmierz** [comment]
Ok, I found something

```stram.getTracks()[0].stop()```

**Comment by cozmo** [comment]
jsQR makes no assumptions about _where_ image data comes from. As such there's not much I can do to help you with this issue as it seems unrelated to jsQR. My best suggestion is to read the docs for the APIs you're using to read the camera. 

Please feel free to re-open if you feel this was closed in error and best of luck with your pausing.

**Comment by ismailah21** [comment]
is it still an issue??
im still havent figure out how to turn off the camera after getting QR data

**Comment by amoungui** [comment]
Thanks gkucmierz for your help

**Comment by L96Github** [comment]
It has to do with your stream source, not jsQR.

Have you tried:
`stream.getTracks().forEach(function(track) {
  track.stop();
});`

**Comment by amoungui** [comment]
no, but i think it is a good idea. i will try this source code.
thanks

**Comment by asimkaya** [comment]
`video.srcObject.getTracks().forEach(function (track) { track.enabled = false });` 
or
`video.srcObject.getTracks().forEach(function (track) { track.stop(); });` u can use it

**Comment by davidleetw** [comment]
video.pause();
video.play();
Both work like a charm for me!
