### ISSUE TITLE
Guide to work with Barcodes

### ISSUE THREAD

**Issue by Darniss** [cozmo/jsQR#179]
Please suggest me to work the same thing in barcode.

**Comment by mtom55** [comment]
This library actually works the best out of all the ones I have tested.  Being able to scan barcodes as well would be very nice

**Comment by ayubUOL** [comment]
@mtom55 how to make it work with barcodes ? I'm unable to find it in docs. QR code is working great. Can you please help to guide me in right direction? Thank you
