### ISSUE TITLE
Powerfull, good work with 'opencv4nodejs'

### ISSUE THREAD

**Issue by pedefe** [cozmo/jsQR#188]
Hi,
I have integrated jsQR with 'opencv4nodejs' and this works very well.
Conversion from OpenCv is :
```
let dstReduced = mat.resize( new cv4.Size(0,0), 0.3, 0.3);
let dstRGBA = dstReduced.cvtColor( cv4.COLOR_BGR2RGBA);
let code = jsQR( dstRGBA.getData(), dstRGBA.cols, dstRGBA.rows, undefined);

```
As you see, from original image (640x480), I resize image from 1/3., QrCode recognition duration changes from 1 second to 60ms.
Great again.
Best regards

**Comment by cozmo** [comment]
Thanks! Love to hear it, and it's neat how simple of a drop in it was. 

If I understand correctly, there is not actually an issue here, and as such I'm going to close this, but thanks for sharing :)
