### ISSUE TITLE
How to decode from image Url?

### ISSUE THREAD

**Issue by xumx** [cozmo/jsQR#19]
Let's say I have a simple remote image url.

How can I use jsQR to decode it? I'm planning to do this on the Node backend. So no Canvas support. 
Do I manually generate the binarizedImage from image buffer?

```
var location = locateQRInBinaryImage(binarizedImage);
if (!location) {
  return;
}
var rawQR = extractQRFromBinaryImage(binarizedImage, location);
if (!rawQR) {
  return;
}
```

It would be good if there is a convenience method to take image link as input.

Thanks!

**Comment by cozmo** [comment]
The method you'll want to use (probably) is `decodeQRFromImage` - https://github.com/cozmo/jsQR#qrjsdecodeqrfromimagedata-width-height

This method accepts an array of rgba values. Where you get that array from doesn't matter. Canvas is one example, but you can also construct it from image blobs. For example if you're fetching a png image from a url you could use https://github.com/photopea/UPNG.js to convert it into the data array using `UPNG.toRGBA8` https://github.com/photopea/UPNG.js#upngtorgba8img. There are similar libraries for any other format you might be dealing with. 

Please let me know if this is helpful and if not I'm happy to provide more clarity. Thanks!
