### ISSUE TITLE
use qr code scanner on http

### ISSUE THREAD

**Issue by mokhtarsoholi** [cozmo/jsQR#194]
hi i have problem with this project this project work well on https but on http camera not allowed how can i run it on the http

**Comment by cozmo** [comment]
Yep, as I've clarified in many a GitHub issue, as well as in the readme, this library [is a QR code scanner, and has no logic for camera access](https://github.com/cozmo/jsQR#a-note-on-webcams). 

getUserMedia doesn't work on http, but jsQR does. That said, if you want to feed jsQR images from a webcam you'll need to figure out how to get an SSL cert. Best of luck and sorry I can't be of more help.
