### ISSUE TITLE
Wrong types for parameters

### ISSUE THREAD

**Issue by marzn** [cozmo/jsQR#20]
There is `number[]` used for `ImageData.data` this should be `Uint8ClampedArray`, see: https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data

**Comment by cozmo** [comment]
I _believe_ this was fixed in https://github.com/cozmo/jsQR/pull/25 - And it's certainly being fixed as we rewrite components ( #31 #28 etc ). 

Please re-open if this isn't the case.
