### ISSUE TITLE
huwai p30 out of focus camera bug

### ISSUE THREAD

**Issue by pcgrozema** [cozmo/jsQR#204]
I want to make a PWA QR reader with ionic / angular.
Your example does not work on all mobiles.
I have a problem with the huwai P30. I see the camera as if it had some zoom and it does not focus well when I bring it closer to the qr or another object and therefore it does not scan the qr code. The mobile camera works well and takes pictures correctly. In fact, if I use other qr apps from playstore with (for example qrdroid) the camera works fine.
Why does it blur on the PWA? That could be happening?

Thanks

**Comment by cozmo** [comment]
This library [is a QR code scanner, and has no logic for camera access](https://github.com/cozmo/jsQR#a-note-on-webcams). 

It sounds like this is an issue with webcams - If you can confirm this is an issue with jsQR - aka not related to the webcam access, but rather to the call of this library, then feel free to clarify in the issue, however if you're just having trouble getting `getUserMedia` to work I'm unfortunately not going to be able to help much.

Closing this issue until it's clear it's an issue with jsQR not the webcam capture. Please comment/re-open if you feel this is in error.
