### ISSUE TITLE
Can I use the camera to read a QR Code?Hi,

### ISSUE THREAD

**Issue by bhaidar** [cozmo/jsQR#22]
Hi,
Can I use the camera to read a QR code using this library?

also, can I parse the data out of the QR code and use a specific set of the data only and not everything?

Thanks

**Comment by marzn** [comment]
I think you should read the [README](https://github.com/cozmo/jsQR/blob/master/README.md) and have a look at the demo. This will answer your first question. The second question could be answered only by yourself.

**Comment by cozmo** [comment]
Agree with @marzn - This library supports taking in image data and leaves it up to the consumer to get that image data from somewhere (such as a camera or a file on disk). The example in the readme uses the camera.
