### ISSUE TITLE
The area of qrcode will affect the results

### ISSUE THREAD

**Issue by aui** [cozmo/jsQR#32]
Thank you very much for your project, and in most cases it works correctly, except for this situation:

**[Error]**

![error](https://user-images.githubusercontent.com/1791748/30677318-affdbd0e-9ebd-11e7-9f4d-1dd67e24a062.jpg)

If the screen is enlarged, it will work properly:

**[Success]**

![success](https://user-images.githubusercontent.com/1791748/30677319-b135f344-9ebd-11e7-9079-8d94e954c34e.jpg)

**Comment by cozmo** [comment]
Hey @aui this is...odd. I've added your test image as part of #35 and I believe this should be fixed by #31. I'll close this issue once the larger image scans successfully.

**Comment by cozmo** [comment]
Happy to report that as of #40 this test passes - https://github.com/cozmo/jsQR/blob/master/test-data/AUTOGEN/summary.json#L218

If you upgrade the library to v1.0.0 you'll get the new code. 

Please re-open if you continue to see the issue.
