### ISSUE TITLE
Does the library work in an Android Cordova app?

### ISSUE THREAD

**Issue by PositronicBrain** [cozmo/jsQR#33]
I tried and it does not seem to work, but I haven't found any explicit reference in the documentation whether the Cordova platform is supported.

**Comment by cozmo** [comment]
@PositronicBrain this library uses vanilla JS and makes no assumptions about where it runs. As such it can run in the browser, in a nodeJS backend, in a react native V8 runtime, etc. 

I don't know much about Cordova but there's nothing that should cause this not to work there. 

If you can provide more details about the failure it could help to provide a place to start investigating.

**Comment by cozmo** [comment]
Closing since there should be nothing in the library that prevents running anywhere javascript can be run. If you have additional details that point to the library feel free to re-open.
