### ISSUE TITLE
Fails to read this image

### ISSUE THREAD

**Issue by iShafayet** [cozmo/jsQR#34]
The reader fails to read this image. I'm certain the parameters are correct.

```
let decoded = jsQR.decodeQRFromImage(qrCode, this.metrics.width, this.metrics.height);
```
No error is thrown. Only the `decoded` variable returns empty string.

![related-image](https://user-images.githubusercontent.com/625311/32051676-689420ea-ba77-11e7-91d2-8e3ca4745671.png)

It's expected to read: BAgAXA==Hhwpy/63yP6bwt1xKDRSAQRpokbYNTsVUX7EZ++mscvjLf0MawexNDY5CKlvcwf/DJosqOpakMLKgxzbEbw/E3wkSK9/

**Comment by cozmo** [comment]
Hey @iShafayet - Thanks for the report. This is pretty cut and dry code - it should definitely decode. I've created a test case for this in #35. My hope is that #31 will fix, and if not one of the rewrites down the line will fix for sure. 

(For context we're currently refactoring the code to fix some bugs like this). 

I'll close this out when the test passes.

**Comment by cozmo** [comment]
Happy to report that as of #40 this test passes - https://github.com/cozmo/jsQR/blob/master/test-data/AUTOGEN/summary.json#L219 

If you upgrade the library to v1.0.0 you'll get the new code. 

Please re-open if you continue to see the issue.
