### ISSUE TITLE
ERROR TypeError: Cannot read property 'score' of undefined

### ISSUE THREAD

**Issue by tiberiuzuld** [cozmo/jsQR#41]
Hello
Using jsQR v1.0.0
I get this error sometimes:
```
ERROR TypeError: Cannot read property 'score' of undefined
    at scripts.bundle.js:10824
    at Array.map (<anonymous>)
    at Object.locate (scripts.bundle.js:10816)
```

From this piece of code:
![image](https://user-images.githubusercontent.com/15310395/35043404-2c97acce-fb95-11e7-9621-2e826b618854.png)

https://github.com/cozmo/jsQR/blob/6763364e549ff790c74c1dd26f99aac4008ee82f/src/locator/index.ts#L344

**Comment by cozmo** [comment]
Good catch! Surprised we didn't see this in testing, the root cause is an image where we find at least 1 finder pattern, but fewer than 3. Added a test and a fix, will publish as `v1.0.1` and update here once it's out.

**Comment by cozmo** [comment]
Update - `v1.0.1` has now been published with the fix for this error. Thanks again for the report.

**Comment by tiberiuzuld** [comment]
Thank you!
