### ISSUE TITLE
the build generates bitmatrix.d.ts in lowercase

### ISSUE THREAD

**Issue by lordnox** [cozmo/jsQR#48]
This will throw an error in all files importing "BitMatrix" as the file can not be found on an OS which cares about this.

I expected bitmatrix.d.ts to be BitMatrix.d.ts

**Comment by lordnox** [comment]
No, the dist folder is checked into github... and the build process will try to write the BitMatrix.d.ts with the generated contents, will find the lowercase file (at least on OSX), and just replace the file contents.

**Comment by cozmo** [comment]
Yea, good catch. Thanks for the PR for fixing.

**Comment by cozmo** [comment]
This has been published as `1.0.3`
