### ISSUE TITLE
Ipad Mini Safari browser Showing Front camera instead of Back and also Ipad Safari is not supported

### ISSUE THREAD

**Issue by kundan52** [cozmo/jsQR#55]
1. Ipad mini Safari Browser opening front camera, OS version 11

2. Iphone 5S Safari its not working, OS version 10.3.3

3. Ipad both Safari and Chrome is not working, OS version 10.1.1

and also I made changes to your code for after scanning camera should close as it was taking more battery, so you add as a optional for library users 

here is my code 

			  var video = document.createElement("video");
			    var canvasElement = document.getElementById("canvas");
			    var canvas = canvasElement.getContext("2d");
			    var loadingMessage = document.getElementById("loadingMessage");
			    var outputContainer = document.getElementById("output");
			    var outputMessage = document.getElementById("outputMessage");
			    //var outputData = document.getElementById("outputData");
				//var outputData = document.getElementById("outputData");

			    function drawLine(begin, end, color) {
			      canvas.beginPath();
			      canvas.moveTo(begin.x, begin.y);
			      canvas.lineTo(end.x, end.y);
			      canvas.lineWidth = 4;
			      canvas.strokeStyle = color;
			      canvas.stroke();
			    }

			    // Use facingMode: environment to attemt to get the front camera on phones
			    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
			      video.srcObject = stream;
			      video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
			      video.play();
			      requestAnimationFrame(tick);
			      localStream = stream;
			    })
			    .catch(function(err) {
			    	console.log(err);
			    	  /* handle the error */
			    });

			    function tick() {
			      loadingMessage.innerText = "⌛ Loading video..."
			      if (video.readyState === video.HAVE_ENOUGH_DATA) {
			        loadingMessage.hidden = true;
			        canvasElement.hidden = false;
			        outputContainer.hidden = false;

			        canvasElement.height = video.videoHeight;
			        canvasElement.width = video.videoWidth;
			        canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
			        var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
			        var code = jsQR(imageData.data, imageData.width, imageData.height);
			        if (code) {
			          drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
			          drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
			          drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
			          drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
			          outputMessage.hidden = true;
			          //outputData.parentElement.hidden = false;
			         // outputData.innerText = code.data;
			          if(code.data != "" && code.data != undefined){
			        	  var dataQR = "qrData=" + code.data;
				          document.cookie = dataQR;
				          
				          vidOff();
				          //var qrGetCookieData =   utility.readCookie("qrData");
				          //alert(qrGetCookieData);  
			          } //else {
			           //alert("qr code not detected")
			         // }
			         
			        } else {
			          outputMessage.hidden = false;
			          //outputData.parentElement.hidden = true;
			        }
			      }
			      requestAnimationFrame(tick);
			      function vidOff() {
				    	video.pause();
				    	video.src = "";
				    	video.srcObject.getVideoTracks().forEach(track => track.stop());
				        console.log("camera off");
				    }
			    }

**Comment by cozmo** [comment]
> 1. Ipad mini Safari Browser opening front camera, OS version 11
If you look at line 18/19 of the code you posted there is a comment explaining exactly this. Specifically `facingMode: "environment"` will try to get the front facing camera. If you don't want that simply remove or change that. 

> Iphone 5S Safari its not working, OS version 10.3.3
> Ipad both Safari and Chrome is not working, OS version 10.1.1
Based on https://caniuse.com/#feat=stream it would seem that `getUserMedia` doesn't work on iOS Safari below 11.2. You may be able to find a polyfill of some form, not sure. As long as you can get image data from somewhere jsQR will scan it.

**Comment by cozmo** [comment]
Closing this issue as I think this should answer the questions, but if you have additional followup I'm happy to re-open.
