### ISSUE TITLE
Its Scanning if it is not QR code also

### ISSUE THREAD

**Issue by kundan52** [cozmo/jsQR#57]
I Tried your Code by scanning Keyboard and partially keyboard's keys its show an output which is wrong behavior of qr code scanner and also its scans partially some qr code and outputs some thing different from the real code, and any think if I keep stable the mobile camera, its scanning.... it. any Idea on this issue

**Comment by cozmo** [comment]
Can you provide example images that scan incorrectly?

**Comment by cozmo** [comment]
Update - was able to get a repro case of this in #68. Closing this issue in favor of tracking there.
