### ISSUE TITLE
QR Codes on Pictures Taken With Phone Then Inserted

### ISSUE THREAD

**Issue by markdude247** [cozmo/jsQR#58]
When I import an image that I've taken with my phone, it usually ends up saying there is no QR Codes, I've tried multiple ways to try to work around this issue even manipulating your own code to try and think the image was a video.

**Comment by cozmo** [comment]
Can you provide example images that fail to decode?

**Comment by cozmo** [comment]
I'm going to close this for lack of activity and because I can't do anything to reproduce it without an image to use. If you have an image that reproduces this issue, or you have additional questions/concerns please re-open/comment. 

Thanks!
