### ISSUE TITLE
 Scanning problem

### ISSUE THREAD

**Issue by we820731** [cozmo/jsQR#59]
![image](https://user-images.githubusercontent.com/31517223/41325276-062a6962-6eec-11e8-8608-deeee94ec7cf.png)
The right picture cannot be scanned.
How to solve this problem?

**Comment by cozmo** [comment]
Ah this is the same issue as #54, bad handling of inverted QR codes (white on black not black on white). I have a fix out for this but have to re-work some of the test framework to support it. I'll keep you posted.

**Comment by cozmo** [comment]
The fix for this (supporting inverted QR codes) was published as version `1.0.5` on npm. Thanks for the report!

**Comment by Doktor-Avalanche** [comment]
I'm trying the demo at https://cozmo.github.io/jsQR/ with my QR-code, which is white on black, but it doesn't decode. Others (Black on White) are decoded fine. Should this demo also decode white on black QR-codes? I also tried the library at my own with the same results. Someone an idea how to resolve?
