### ISSUE TITLE
Cant decode 

### ISSUE THREAD

**Issue by ezequiel454** [cozmo/jsQR#61]
I could not decode
![aa](https://user-images.githubusercontent.com/11526507/41552043-001c1fea-7304-11e8-9320-59c1e0c24718.jpg)
![cc6](https://user-images.githubusercontent.com/11526507/41552044-004285c2-7304-11e8-8ef6-02e757763b27.jpg)

 this image.

**Comment by cozmo** [comment]
Huh, this is an odd one, will take a look. Thanks!

**Comment by cozmo** [comment]
Thanks for reporting this! It turns out that QR code had ECI encoding which we didn't handle. We added support for ECI in #71 and published it on npm as `1.1.0`. Let me know if you have any additional issues.
