### ISSUE TITLE
Sometimes can't capture\decode

### ISSUE THREAD

**Issue by mikkiek** [cozmo/jsQR#63]
In some cases, especially when few QR cordes close to each other it decods in wrong way
http://prntscr.com/jwwr3o
or
http://prntscr.com/jwws79

**Comment by cozmo** [comment]
Thanks for the reproduction case! Going to try to track this bug down because I think it's the same as #64

**Comment by cozmo** [comment]
Tracking this in a central issue (with repro case) - #68. Going to close this issue in favor of that one.
