### ISSUE TITLE
Face sends chinese data?

### ISSUE THREAD

**Issue by videroCat** [cozmo/jsQR#64]
My face returns some weird data.

https://prnt.sc/jxhmtz

Happened while i was just jiggling around in my chair.

**Comment by cozmo** [comment]
Do you have the image that causes this decoding? We have a hunch of what's causing it but can't debug without the source image.

**Comment by videroCat** [comment]
I might try to get a shot of recreating the scene.

Ill try to take a snapshot of the moment it trys to decode my face apparently.


Greets,
Christopher Urban 
Software Development

**Comment by cozmo** [comment]
Sounds good! I hope you don't mind but I'm going to close this issue for now, seeing as there's not much to do without a repro case. 

I'd love to track this bug down though so please do re-open if you can. One thing you could try is changing whatever scanning code you're using to dump the frame as soon as it gets a valid scan. Might be as easy as calling `window.open(`[`toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)`)` on the canvas tag?

**Comment by cozmo** [comment]
Actually though this seems like it could be the same issue as #63 so may just try to use the image provided in that issue.

**Comment by kazzkiq** [comment]
Just to add a little more info on the issue:

I've experienced it too and its not triggered by any specific image. Sometimes I start scanning and while I'm still reaching to the QR code in the desk it somehow identifies reflexes/patterns on objects (wall, desk, cloth, etc) as valid QR code that translates to Chinese characters.

I'm not sure how exactly the code defines what is a QR code and what isn't, but perhaps we could have a flag `threshold` where you define the level of confidence so the code only returns if its really sure its a real QR Code.

An (ugly) workaround I'm willing to use at the moment is actually identify any Chinese characters in the return. If there is any of them, I simply ignore it and keep the function running until something comes back in latin alphabet (which its the language I work with).

**Comment by videroCat** [comment]
Yep,

And the weird thing is, it isn’t even evaluating a square, sometimes I get 2 Lines connected to the top in a weird place on the camera, sometimes I get a triangle.
Christopher Urban 
Software Development

mobile: +49 15253438914 | skype: curban@videro.com
VIDERO AG	VIDERO Inc.	
Pfarrer-Reukes-Str. 7 
48599 Gronau GERMANY 
Fon: +49 2562 93980 
www.videro.de <http://videro.de/>	139 Maryland St. 
El Segundo, CA 90245 USA 
Fon: +1 424 277 0800 
www.videro.com <http://videro.com/>	AG Coesfeld HRB 10675 
Vorstand: Johannes Büld (Vorsitzender) 
& Andre Brinkmöller 
Aufsichtsratsvorsitzender: Rainer Schlief
Folgen Sie uns:                             
 <https://www.facebook.com/Videro-your-ideas-on-screen-102198719860456/>  <https://twitter.com/videro>  <https://www.youtube.com/user/VideroDigitalSignage>

**Comment by videroCat** [comment]
Yep,

And the weird thing is, it isn’t even evaluating a square, sometimes I get 2 Lines connected to the top in a weird place on the camera, sometimes I get a triangle.

**Comment by cozmo** [comment]
Was able to create a reproduction case in #68. Feel free to follow along there.
