### ISSUE TITLE
Incorrectly finds QR codes and returns malformed data

### ISSUE THREAD

**Issue by cozmo** [cozmo/jsQR#68]
Several issues have come with with the library incorrectly locating QR codes where there aren't any, returning malformed data (often manifesting as Chinese characters). 

This is an central issue to track these issue on. I've been able to reproduce the error with this image 
![malformed](https://user-images.githubusercontent.com/696340/42019355-cd6e6a68-7a69-11e8-82be-348c4c09ea5a.png). 

We'll use this image to try to catch the issue (thinking we're not correctly detecting error correction levels).

**Comment by cozmo** [comment]
Hey @mikkiek @kundan52 @videroCat @kazzkiq have consolidated all your issues about incorrectly finding codes and returning malformed data here. Hoping that with a repro case it'll be easy to track down but we'll see 🤞

**Comment by cozmo** [comment]
This has been fixed and is being published as `1.0.6`). Thanks for the reports all!

**Comment by kazzkiq** [comment]
Tested locally and it works perfectly, thanks!
