### ISSUE TITLE
Throwing an error jsQR not defined 

### ISSUE THREAD

**Issue by kundan52** [cozmo/jsQR#72]
I am trying to implement your js in a jsp page,
where all other methods in one js and the two js i am calling in JSP page

first: jsQR.js
second my javascript file

when I try to upload it throws and error 
the JS in AMD, how to use it as non AMD 

	var code = jsQR(imageData.data, imageData.width, imageData.height);

**Comment by cozmo** [comment]
What is the error it throws?

**Comment by kundan52** [comment]
oh Sorry, jsQR is not defined

**Comment by cozmo** [comment]
if you include jsQR.js it should define it in the global scope, so `window.jsQR` would be set. 

You can see an example of this on the demo page - https://cozmo.github.io/jsQR/. 

I'm not familiar at all with JSP, but there shouldn't be anything specific about jsQR I don't think? Without further context I'm not sure how to help.

**Comment by kundan52** [comment]
Ok, I Understand it,  now I am using require.js and my issue is resolved
