### ISSUE TITLE
Can't decode this image

### ISSUE THREAD

**Issue by satrio1256** [cozmo/jsQR#77]
For some strange reason, I couldn't decode this image.

![screenshot from 2018-07-18 00-01-17](https://user-images.githubusercontent.com/12686339/42833291-e10917d0-8a1d-11e8-8eea-70a0370313d3.png)

Would you mind to check? Thank you.

Edit : 
- Already trying with various angle and camera, still not working for me.. But the other qr (that I have) works perfectly.
- Tested it with another scanner, it works there

**Comment by cozmo** [comment]
Hey! Thanks for the report. This is an interesting issue. Your QR code is missing the "terminator byte" which was believed to be required. That said, reading [this](https://www.thonky.com/qr-code-tutorial/data-encoding#add-a-terminator-of-0s-if-necessary) makes it sound as if it's optional, and what is more, may be shorter than the 4 bytes we expect.

I made a PR (#80) to fix it, and have confirmed this fixes the above QR code, but I may want to change it a bit before merging depending on my rereading of the spec.

**Comment by satrio1256** [comment]
Alright then. I'll wait for the final merge on the master branch.

Thanks for the follow-up :)

**Comment by cozmo** [comment]
This has been published on npm as `1.1.1`. Thanks for the report, and sorry for the trouble. Going to close this issue but if for some reason there's still an issue please feel free to re-open.
