### ISSUE TITLE
Not Able Scan QR when there is more light

### ISSUE THREAD

**Issue by haresh93** [cozmo/jsQR#83]
I am using this library in my application to scan QR code in a manufacturing industry to know the status of the product in the manufacturing process and to store details of the unit and retrieve and show it when needed.

Now the issue that i am facing is that while testing the qr detection in my office it was working great, but when i check it live in the industry, the qr code code is not detected. but with normal apps i was able to scan the QR. 

How can i solve this problem??

**Comment by globophobe** [comment]
Maybe consider (adaptive) thresholding before searching for the QR code.

**Comment by haresh93** [comment]
What do you mean by adaptive thresholding??? Like???

**Comment by globophobe** [comment]
Thresholding can help if there is too much/little light. I have used OpenCv for this purpose with Python.  JS is also available. https://docs.opencv.org/3.4/d7/dd0/tutorial_js_thresholding.html

**Comment by haresh93** [comment]
I guess Thresholding is a part of jsQR code...presently i am just passing the image data to jsQR what you are saying is to perform adaptive threshold on the image and pass it to jsQR???

**Comment by cozmo** [comment]
The binarization step already does some adaptive thresholding, but it isn't perfect right now. @haresh93 could you provide an image that you think should scan but doesn't? That's going to be the easier way to debug.

**Comment by cozmo** [comment]
@haresh93 I'm going to close this due to lack of response, and we can't debug without an image. That said I'd really like to solve this issue so please re-open with a test case if you can?
