### ISSUE TITLE
web camera scan qr

### ISSUE THREAD

**Issue by avmaisak** [cozmo/jsQR#84]
Hello.
Could you provide some code examples, how to scan qr code using web camera live view. 
For ex. via video html tag
Thank you.

**Comment by cozmo** [comment]
Does the [note on webcams](https://github.com/cozmo/jsQR#a-note-on-webcams) or [demo](https://cozmo.github.io/jsQR/) from the readme provide what you're looking for?

**Comment by avmaisak** [comment]
oops. sorry for flood
