### ISSUE TITLE
The JSQR code is not able to scan but same if i am able to do with zxing or webqr.com 

### ISSUE THREAD

**Issue by kundan52** [cozmo/jsQR#85]
try this code 

checkout this code using zxing and webqr it working, but not working in jsQR

**Comment by cozmo** [comment]
Can you try to re-uploaded the image? It doesn't appear to be attached currently.

**Comment by cozmo** [comment]
@kundan52 I'm going to close this due to lack of response, and we can't debug an image without seeing the image after all. That said please do re-open with the image if you can, I'd love to fix this.
