### ISSUE TITLE
always getting "Malformed data passed to binarizer."

### ISSUE THREAD

**Issue by erikparr** [cozmo/jsQR#88]
Hi I am always getting the same malformed data error. Even when I simply create an Uint8Array filled with RGBA values I get the same error.  like this: 
`pixelBuffer = new Uint8Array(textureSize * textureSize * 4);`

I have tried using Uint8ClampedArray with the same result. What am I doing wrong here?

I made a fiddle [here](https://jsfiddle.net/triangle_shifter/wdtpsnyq/) with my project that throws the error. The error is thrown when you click on the screen. 

To give you some background info on the fiddle, I am using the 3D graphics library Three.js to scan QR within the 3d environment (will be used for augmented reality). In the scene, the camera is being rendered out to a DataTexture like in [this example](https://threejs.org/examples/#webgl_framebuffer_texture). The idea is to use the Uint8Array texture data to give to jsQR.

Thanks

**Comment by ZhuXiaomin** [comment]
jsQR v1.1.0 might solve your problem. It works for me.

**Comment by WilliamKatz** [comment]
@erikparr, hey did you figure out what was wrong? Im getting a similar error

**Comment by liuminghui2017** [comment]
// imageData = new Uint8ClampedArray()
// imageData = canvas.getImageData()
and then, call like this
jsQR(imageData.data, width, height)

**Comment by Coande** [comment]
I also met this error.
```
const code = jsQR(imageData, width, height, options?);
```
`width` and `height` should be a int value, not a float.

**Comment by mubaidr** [comment]
Any update?

**Comment by vladikoff** [comment]
I had to change to the following ` new Uint8ClampedArray(png.toRGBA8(data)[0])` after decoding the png buffer, then it worked. Example:
```
    const data = png.decode(buffer);
    const out = {
      data: new Uint8ClampedArray(png.toRGBA8(data)[0]),
      height: data.height,
      width: data.width,
    };

    const code = jsQR(out.data, out.width, out.height);
```

**Comment by rixrix** [comment]
thanks @vladikoff your solution worked for me, don't know why this ticket was closed

I'm the following versions:

Node v10.16.0
Npm v6.9.0

**Comment by rigwild** [comment]
For me, it was passing `imageData` instead of `imageData.data` (lmao)



```ts
const image = new Image()
image.src = blobURL
await new Promise(resolve => image.addEventListener('load', resolve))

const canvas = document.createElement('canvas')
canvas.width = image.width
canvas.height = image.height
const context = canvas.getContext('2d')

context.imageSmoothingEnabled = false
context.drawImage(image, 0, 0)
const imageData = context.getImageData(0, 0, image.width, image.height)

const code = jsQR(imageData.data, image.width, image.height)
```

**Comment by jeronimoek** [comment]
Just in case this helps someone, the code that throws this error is this:
`if (data.length !== width * height * 4) {
        throw new Error("Malformed data passed to binarizer.");
    }`
Which means that basically, if your Uint8ClampedArray has less elements than your width * height * 4, it throws an error. I still haven't found how to make it match

**Comment by jeronimoek** [comment]
What I needed was a way to convert a src string into an uint8clampedarray, these answers worked for me: https://stackoverflow.com/questions/45365571/convert-an-image-to-imagedata-uint8clampedarray

No matter what kind of image you are working with, like the docs say, you just need an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) object

**Comment by KangHidro** [comment]
If you want to read QR code in backend NodeJS, where not support `document.createElement`:

`npm i buffer-image-size canvas jsqr`
`buffer-image-size` is optional

```
import jsQR from 'jsqr';
import * as sizeOf from 'buffer-image-size';
import * as Canvas from 'canvas';
```

```
async readQr() {
...
// First, reading "imgFile" as Buffer or Base64

const dimensions = sizeOf(imgFile.buffer); // Or sizeOf(Buffer.from(<base64>, 'base64'));

const canvas = Canvas.createCanvas(dimensions.width, dimensions.height);
const ctx = canvas.getContext('2d');

ctx.imageSmoothingEnabled = false;
ctx.drawImage(await Canvas.loadImage(imgFile.buffer), 0, 0);
// Or ctx.drawImage(await Canvas.loadImage(<base64>), 0, 0);
const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);

const qr = jsQR(imgData.data, dimensions.width, dimensions.height);
console.log(qr);
}
```

**Comment by ColinFrick** [comment]
The problem for me were png files without alpha channel.
Using sharp I added the channel if missing:
```javascript
import sharp from 'sharp';
import jsQR from "jsqr";
import process from 'node:process';

const {data, info} = await sharp(path)
    .ensureAlpha()
    .raw()
    .toBuffer({resolveWithObject: true});

const code = jsQR(new Uint8ClampedArray(data.buffer), info.width, info.height);
console.log(code);
```
