### ISSUE TITLE
Does jsQR only work on https?

### ISSUE THREAD

**Issue by gxlonline** [cozmo/jsQR#91]
I have copy/paste all the code from "https://cozmo.github.io/jsQR/" into my rails application. In the development environment, I user the ip:3000 to visit the site, but I can't get the image:

http://192.168.226.140:3000/processes/scan
![20180816141636](https://user-images.githubusercontent.com/1692874/44191786-45cfa000-a15f-11e8-9622-8a6d6c8245cc.jpg)

I have save the html to local from demo, then use the browser to open it, It's work fine.
I'm not too familiar with JS. Please give me some advice. thanks.

**Comment by satrio1256** [comment]
Not the jsQR but the getUserMedia() function from your browser. 
To use getUserMedia() function (at least in newest version of chrome) you need to use HTTPS. Use localhost/your_work_dir to use it locally.

**Comment by cozmo** [comment]
This is covered by our [`note on webcams`](https://github.com/cozmo/jsQR#a-note-on-webcams) - jsQR itself works in any js context (server side, client side etc). That said, `getUserMedia` and some associated browser APIs have additional constraints (like @satrio1256 mentions). Closing this, and would refer you to stackoverflow and or MDN documentation for questions about browser webcam APIs and their limitations. That said - @satrio1256's comment matches my understanding, which is Chrome at least requires pages to be on https or localhost for `getUserMedia` calls to work. 

If you think this was closed in error or you have additional questions feel free to re-open etc. 

Thanks!
