### ISSUE TITLE
How support 2D Data Matrix Code scan

### ISSUE THREAD

**Issue by Jone-C** [cozmo/jsQR#93]
Hello cozmo,

About jsQR project for your share, it can very efficient work, can any method support DM(DATA MATRIX) code ?

**Comment by cozmo** [comment]
Hey @Jone-C - Unfortunately jsQR only supports QR codes, and that will probably not change in the future. I'd love if someone were to create a JSDataMatrix library, and there may be some parts of jsQR that could be useful (binarize and decode for example), but this would almost certainly be a separate library and not part of jsQR. 

Happy to answer any additional questions if you have.

**Comment by Jone-C** [comment]
cozmo, thanks for your reply. Now I build a new schema , using JS decode QR Code and rely Ajax submit BASE64 image data to web server decode by zxing. That can adapt with our application scene.
